apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata:
 name: lab-8
spec:
 containers:
 - name: bear
   image: supergiantkir/animals:bear
   ports:
   - containerPort: 80
   volumeMounts:
   - name: app-storage
     mountPath: /data/redis
 - name: springapp
   image: yanivomc/spring-music:latest
   ports:
   - containerPort: 8080
   volumeMounts:
   - name: app-storage
     mountPath: /app/data
 volumes:
 - name: app-storage
   hostPath:
           path: /home/ubuntu/storage
           type: Directory
